# Generated by Django 2.2.5 on 2021-02-15 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='description',
        ),
        migrations.AddField(
            model_name='calendar',
            name='color',
            field=models.CharField(default='royalblue', max_length=50),
            preserve_default=False,
        ),
    ]
