# Generated by Django 2.2.5 on 2021-02-15 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='maps',
            new_name='Map',
        ),
    ]
