# Generated by Django 3.1.5 on 2021-02-16 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='address2',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='book',
            name='content',
        ),
        migrations.RemoveField(
            model_name='book',
            name='date1',
        ),
        migrations.RemoveField(
            model_name='book',
            name='date2',
        ),
    ]
